---
  server:
    port: 8080

  spring:
    datasource:
      url: jdbc:postgresql://localhost/task_tracker
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver


    jpa:
      hibernate:
        ddl-auto: update
